name: puppeteer-es6modules-typescript-jest

on: 
  push:
  schedule:
    - cron: '0 0 2-30/2 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, build, and test
      run: |
        npm ci
        npm run test
      env:
        CI: true
